/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eecs448_project;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.*;

/**
 *
 * @author Danilo
 */
public class RPGForm extends javax.swing.JFrame {

    
    
    float count1=0;
    float time=0;

  
    /**
     * Creates new form RPGForm
     */
    public RPGForm() {
        time++;

        initComponents();
                  this.setAlwaysOnTop(true);
        Toolkit tk=Toolkit.getDefaultToolkit();
        int x = (int) tk.getScreenSize().getWidth();
        int y = (int) tk.getScreenSize().getHeight();
        this.setSize(x, y);
        this.setAlwaysOnTop(false);
        this.setAutoRequestFocus(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPG");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Normal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 450, 250, 29);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jButton4.setText("jButton4");
        jPanel1.add(jButton4);
        jButton4.setBounds(50, 20, 170, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo\\Desktop\\Pleura\\imagens\\matrix.gif")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1318, 1024);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(940, 20, 210, 440);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Option1");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusCycleRoot(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 470, 90, 23);

        jButton2.setText("Option2");
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 470, 90, 23);

        jButton3.setText("Option3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 470, 90, 23);

        jPanel2.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo\\Desktop\\Projeto Gustavo\\Imãs-2014-09-20\\animacoes\\atrair\\100%\\1.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel2.add(jLabel4);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 400, 1160, 150);

        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1160, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
count1++;    

              if(count1==1){
            
  jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo\\Desktop\\Software Engineering\\Project\\0010.gif")); // NOI18N
       jLabel1.setText("Attack");  
       
       jButton1.setLocation(100, 200);
       jButton1.setSize(100, 30);
       jButton1.setText("1");
       jButton1.setBackground(Color.RED);
       jButton1.setOpaque(false);

       int b=0;
       while(b<1000){
           b++;
           jPanel1.setSize(b, b);
       }


        //jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Danilo\\Desktop\\Software Engineering\\Project\\0010.gif")); // NOI18N
   
}
              
       jButton1.setText(""+count1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RPGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RPGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RPGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RPGForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RPGForm().setVisible(true);
           
     
         
            }
          
        });
        


        
  
        
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}